server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    h2:
      console:
        enabled: true
        path: /h2-console
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: teste
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    initialization-mode: always
    data: classpath:schema.sql
  output:
    ansi:
      enabled: Always
  rabbitmq:
    name: "mensageria-teste"
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange:
        name: my_exchange
        type: direct
      routing-key: my_routing_key
    listener:
      simple:
        queue-name: my_queue
        auto-startup: true
atlante:
  security:
    public-endpoints:
      - /public
      - /swagger-ui.html
      - /swagger-ui/**
      - /v3/api-docs
      - /v3/api-docs/**
      -

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
---